Repository planetarium/wncg-staking-interface, pull requests merged in 2024-01, with the labels that each got.

#54 Fix: TotalStaked value update
  config/index.ts
  hooks/balancer/useExitForm.ts
  hooks/queries/useFetchPrices.ts
  hooks/queries/useFetchTotalStaked.ts
Labels: Extra Small

#55 Config: Change testing library to Vitest from Jest.
  .github/workflows/codecov.yaml
  .gitignore
  .yarnrc.yml
  jest.config.ts
  jest.setup.js
  package.json
  tests/hooks/useFetchTotalStaked.test.tsx
  tests/utils/calcApr.test.ts
  tsconfig.json
  vitest.config.ts
  yarn.lock
Labels: enhancement, Small

#56 Fix: Use Yarn v1 again, Update test / codecov scripts
  .babelrc.sample
  .yarnrc.yml
  package.json
  yarn.lock
Labels: bug, Extra Small

#57 fix: revert to cjs
  package.json
  yarn.lock
Labels: bug, Extra Small
